name: Delete Rows Daily

on:
  schedule:
    - cron: '0 0 * * *'  # This means every day at midnight UTC
  workflow_dispatch:

jobs:
  delete-rows:
    runs-on: ubuntu-latest
    steps:
      - name: Call Edge Function
        run: |
          curl -X DELETE -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" "${{ secrets.SUPABASE_URL }}/functions/v1/delete-all-shared-json"
